from apps.expenses.models import *
Units(unit="kg", description="kilograme").save()
Units(unit="ltr", description="liter").save()
Units(unit="pkt", description="packet").save()
ItemTags(name="Alcohol").save()
ItemTags(name="Entertainment").save()
ItemTags(name="Electronics").save()
ItemTags(name="Food").save()
ItemTags(name="Lunch").save()
ItemTags(name="Outdoor").save()
ItemTags(name="Adventure").save()
ItemTags(name="Transport").save()
ItemTags(name="Fuel").save()
ItemTags(name="Wood").save()
ItemTags(name="Climbing").save()
ItemTags(name="Biking").save()
ItemTags(name="Stationary").save()
ItemTags(name="Furniture").save()
ItemTags(name="Bedding").save()
ItemTags(name="Kitchen").save()
ItemTags(name="Eating out").save()
ItemTags(name="Cheese").save()
ItemTags(name="Cold cuts").save()
ItemTags(name="Household").save()
ItemTags(name="Salad").save()
ItemTags(name="Meet").save()
ItemTags(name="Toiletries").save()
ItemTags(name="Medicine").save()
ItemTags(name="Sweets").save()
ItemTags(name="Tea time").save()
ItemTags(name="Cooking").save()
ItemTags(name="Fireplace").save()
ItemTags(name="Herbs").save()
ItemTags(name="Ready meals").save()
PurchaseTags(name="Groceries").save()
PurchaseTags(name="Furniture").save()
PurchaseTags(name="Electronics").save()
PurchaseTags(name="Household").save()
PurchaseTags(name="Entertainment").save()
PurchaseTags(name="Eating out").save()
PurchaseTags(name="Pharmacy").save()
PurchaseTags(name="Adventure").save()
PurchaseTags(name="Transport").save()
